unit uDDLGenerator;

{$mode objfpc}{$H+}

interface

uses
  SysUtils, Classes,
  uAppTypes, uModelSchemaObject;

type
  { TDDLGenerator }
  TDDLGenerator = class
  private
    class function QuoteIdent(const AIdent: string; const ADriverType: TDBDriverType): string;
    class function FormatColumnDefinition(AColumn: TSchemaColumn; const ADriverType: TDBDriverType): string;
    class function FormatQualifiedTableName(const ASchema, ATable: string; const ADriverType: TDBDriverType): string;
  public
    // Pembuatan DDL Objek Skema
    class function GenerateCreateTable(ATable: TSchemaObject; const ADriverType: TDBDriverType): string;
    class function GenerateCreateIndex(AIndex: TSchemaIndex; const ASchema: string; const ADriverType: TDBDriverType): string;
    class function GenerateAddForeignKey(AForeignKey: TSchemaForeignKey; const ASchema: string; const ADriverType: TDBDriverType): string;

    // Operasi Alter & Drop
    class function GenerateDropTable(const ASchema, ATable: string; const ADropIfExists: Boolean; const ACascade: Boolean; const ADriverType: TDBDriverType): string;
    class function GenerateDropView(const ASchema, AView: string; const ADropIfExists: Boolean; const ADriverType: TDBDriverType): string;
    class function GenerateAddColumn(const ASchema, ATable: string; AColumn: TSchemaColumn; const ADriverType: TDBDriverType): string;
    class function GenerateDropColumn(const ASchema, ATable, AColumnName: string; const ADriverType: TDBDriverType): string;
    class function GenerateDropIndex(const ASchema, AIndexName, ATableName: string; const ADriverType: TDBDriverType): string;
    class function GenerateTruncateTable(const ASchema, ATable: string; const ADriverType: TDBDriverType): string;
  end;

implementation

{ TDDLGenerator }

class function TDDLGenerator.QuoteIdent(const AIdent: string; const ADriverType: TDBDriverType): string;
begin
  if AIdent = '' then Exit('');
  case ADriverType of
    dtMySQL, dtMariaDB:
      Result := '`' + AIdent + '`';
    dtPostgreSQL, dtSQLite, dtFirebird:
      Result := '"' + AIdent + '"';
    else
      Result := '"' + AIdent + '"';
  end;
end;

class function TDDLGenerator.FormatQualifiedTableName(const ASchema, ATable: string; const ADriverType: TDBDriverType): string;
begin
  if (ASchema <> '') and (ADriverType in [dtPostgreSQL]) then
    Result := QuoteIdent(ASchema, ADriverType) + '.' + QuoteIdent(ATable, ADriverType)
  else
    Result := QuoteIdent(ATable, ADriverType);
end;

class function TDDLGenerator.FormatColumnDefinition(AColumn: TSchemaColumn; const ADriverType: TDBDriverType): string;
var
  TypeStr: string;
  UpperType: string;
begin
  UpperType := UpperCase(Trim(AColumn.DataType));
  TypeStr := UpperType;

  // Format Tipe Data Berparameter (Length, Precision, Scale)
  if (AColumn.Length > 0) and (Pos('VARCHAR', UpperType) > 0) or (Pos('CHAR', UpperType) > 0) then
    TypeStr := Format('%s(%d)', [UpperType, AColumn.Length])
  else if (AColumn.Precision > 0) and ((Pos('DECIMAL', UpperType) > 0) or (Pos('NUMERIC', UpperType) > 0)) then
  begin
    if AColumn.Scale > 0 then
      TypeStr := Format('%s(%d, %d)', [UpperType, AColumn.Precision, AColumn.Scale])
    else
      TypeStr := Format('%s(%d)', [UpperType, AColumn.Precision]);
  end;

  // Penanganan Auto Increment per DBMS
  if AColumn.IsAutoIncrement then
  begin
    case ADriverType of
      dtSQLite:
      begin
        if AColumn.IsPrimaryKey then
        begin
          Result := Format('%s INTEGER PRIMARY KEY AUTOINCREMENT', [QuoteIdent(AColumn.Name, ADriverType)]);
          Exit;
        end;
      end;
      dtPostgreSQL:
      begin
        if Pos('BIGINT', UpperType) > 0 then
          TypeStr := 'BIGSERIAL'
        else if (Pos('SMALLINT', UpperType) > 0) then
          TypeStr := 'SMALLSERIAL'
        else
          TypeStr := 'SERIAL';
      end;
      dtMySQL, dtMariaDB:
        TypeStr := TypeStr + ' AUTO_INCREMENT';
      dtFirebird:
        TypeStr := TypeStr + ' GENERATED BY DEFAULT AS IDENTITY';
    end;
  end;

  Result := QuoteIdent(AColumn.Name, ADriverType) + ' ' + TypeStr;

  // Nullability
  if not AColumn.IsNullable then
    Result := Result + ' NOT NULL'
  else if (ADriverType in [dtMySQL, dtMariaDB]) and (Pos('TIMESTAMP', UpperType) > 0) then
    Result := Result + ' NULL';

  // Default Value
  if Trim(AColumn.DefaultValue) <> '' then
  begin
    if (Pos('DEFAULT', UpperCase(AColumn.DefaultValue)) = 1) then
      Result := Result + ' ' + AColumn.DefaultValue
    else
      Result := Result + ' DEFAULT ' + AColumn.DefaultValue;
  end;

  // Komentar Kolom (MySQL / MariaDB Inline Comment)
  if (AColumn.Comment <> '') and (ADriverType in [dtMySQL, dtMariaDB]) then
    Result := Result + ' COMMENT ''' + StringReplace(AColumn.Comment, '''', '''''', [rfReplaceAll]) + '''';
end;

class function TDDLGenerator.GenerateCreateTable(ATable: TSchemaObject; const ADriverType: TDBDriverType): string;
var
  Lines: TStringList;
  PKCols: TStringList;
  I, J: Integer;
  ColDef, JoinedPK, TargetTable: string;
  Col: TSchemaColumn;
  FK: TSchemaForeignKey;
  FKCols, RefCols: string;
begin
  Lines := TStringList.Create;
  PKCols := TStringList.Create;
  try
    TargetTable := FormatQualifiedTableName(ATable.SchemaName, ATable.Name, ADriverType);
    Lines.Add(Format('CREATE TABLE %s (', [TargetTable]));

    // 1. Kolom
    for I := 0 to ATable.Columns.Count - 1 do
    begin
      Col := ATable.Columns[I];
      ColDef := '    ' + FormatColumnDefinition(Col, ADriverType);

      // Catat Primary Key (jika bukan SQLite autoincrement yang sudah di-inline)
      if Col.IsPrimaryKey and not ((ADriverType = dtSQLite) and Col.IsAutoIncrement) then
        PKCols.Add(QuoteIdent(Col.Name, ADriverType));

      if (I < ATable.Columns.Count - 1) or (PKCols.Count > 0) or (ATable.ForeignKeys.Count > 0) then
        ColDef := ColDef + ',';

      Lines.Add(ColDef);
    end;

    // 2. Primary Key Constraint
    if PKCols.Count > 0 then
    begin
      JoinedPK := '';
      for I := 0 to PKCols.Count - 1 do
      begin
        if I > 0 then JoinedPK := JoinedPK + ', ';
        JoinedPK := JoinedPK + PKCols[I];
      end;

      if ATable.ForeignKeys.Count > 0 then
        Lines.Add(Format('    PRIMARY KEY (%s),', [JoinedPK]))
      else
        Lines.Add(Format('    PRIMARY KEY (%s)', [JoinedPK]));
    end;

    // 3. Foreign Key Constraints
    for I := 0 to ATable.ForeignKeys.Count - 1 do
    begin
      FK := ATable.ForeignKeys[I];
      FKCols := '';
      for J := 0 to FK.ColumnNames.Count - 1 do
      begin
        if J > 0 then FKCols := FKCols + ', ';
        FKCols := FKCols + QuoteIdent(FK.ColumnNames[J], ADriverType);
      end;

      RefCols := '';
      for J := 0 to FK.RefColumnNames.Count - 1 do
      begin
        if J > 0 then RefCols := RefCols + ', ';
        RefCols := RefCols + QuoteIdent(FK.RefColumnNames[J], ADriverType);
      end;

      ColDef := Format('    CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)', [
        QuoteIdent(FK.Name, ADriverType),
        FKCols,
        FormatQualifiedTableName(ATable.SchemaName, FK.RefTableName, ADriverType),
        RefCols
      ]);

      if FK.OnDelete <> '' then
        ColDef := ColDef + ' ON DELETE ' + FK.OnDelete;
      if FK.OnUpdate <> '' then
        ColDef := ColDef + ' ON UPDATE ' + FK.OnUpdate;

      if I < ATable.ForeignKeys.Count - 1 then
        ColDef := ColDef + ',';

      Lines.Add(ColDef);
    end;

    // Penutup Create Table
    if (ADriverType in [dtMySQL, dtMariaDB]) and (ATable.Comment <> '') then
      Lines.Add(Format(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=''%s'';', [
        StringReplace(ATable.Comment, '''', '''''', [rfReplaceAll])
      ]))
    else
      Lines.Add(');');

    // 4. Komentar Kolom/Tabel (PostgreSQL Style)
    if ADriverType = dtPostgreSQL then
    begin
      if ATable.Comment <> '' then
        Lines.Add(Format('COMMENT ON TABLE %s IS ''%s'';', [
          TargetTable, StringReplace(ATable.Comment, '''', '''''', [rfReplaceAll])
        ]));

      for I := 0 to ATable.Columns.Count - 1 do
      begin
        Col := ATable.Columns[I];
        if Col.Comment <> '' then
          Lines.Add(Format('COMMENT ON COLUMN %s.%s IS ''%s'';', [
            TargetTable, QuoteIdent(Col.Name, ADriverType),
            StringReplace(Col.Comment, '''', '''''', [rfReplaceAll])
          ]));
      end;
    end;

    // 5. Create Indexes
    for I := 0 to ATable.Indexes.Count - 1 do
    begin
      if not ATable.Indexes[I].IsPrimary then
      begin
        Lines.Add('');
        Lines.Add(GenerateCreateIndex(ATable.Indexes[I], ATable.SchemaName, ADriverType));
      end;
    end;

    Result := Lines.Text;
  finally
    PKCols.Free;
    Lines.Free;
  end;
end;

class function TDDLGenerator.GenerateCreateIndex(AIndex: TSchemaIndex; const ASchema: string; const ADriverType: TDBDriverType): string;
var
  Cols: string;
  I: Integer;
  UniqStr: string;
begin
  Cols := '';
  for I := 0 to AIndex.Columns.Count - 1 do
  begin
    if I > 0 then Cols := Cols + ', ';
    Cols := Cols + QuoteIdent(AIndex.Columns[I], ADriverType);
  end;

  if AIndex.IsUnique then
    UniqStr := 'UNIQUE '
  else
    UniqStr := '';

  Result := Format('CREATE %sINDEX %s ON %s (%s);', [
    UniqStr,
    QuoteIdent(AIndex.Name, ADriverType),
    FormatQualifiedTableName(ASchema, AIndex.TableName, ADriverType),
    Cols
  ]);
end;

class function TDDLGenerator.GenerateAddForeignKey(AForeignKey: TSchemaForeignKey; const ASchema: string; const ADriverType: TDBDriverType): string;
var
  Cols, RefCols, SQL: string;
  I: Integer;
begin
  Cols := '';
  for I := 0 to AForeignKey.ColumnNames.Count - 1 do
  begin
    if I > 0 then Cols := Cols + ', ';
    Cols := Cols + QuoteIdent(AForeignKey.ColumnNames[I], ADriverType);
  end;

  RefCols := '';
  for I := 0 to AForeignKey.RefColumnNames.Count - 1 do
  begin
    if I > 0 then RefCols := RefCols + ', ';
    RefCols := RefCols + QuoteIdent(AForeignKey.RefColumnNames[I], ADriverType);
  end;

  SQL := Format('ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)', [
    FormatQualifiedTableName(ASchema, AForeignKey.TableName, ADriverType),
    QuoteIdent(AForeignKey.Name, ADriverType),
    Cols,
    FormatQualifiedTableName(ASchema, AForeignKey.RefTableName, ADriverType),
    RefCols
  ]);

  if AForeignKey.OnDelete <> '' then
    SQL := SQL + ' ON DELETE ' + AForeignKey.OnDelete;
  if AForeignKey.OnUpdate <> '' then
    SQL := SQL + ' ON UPDATE ' + AForeignKey.OnUpdate;

  Result := SQL + ';';
end;

class function TDDLGenerator.GenerateDropTable(const ASchema, ATable: string; const ADropIfExists: Boolean; const ACascade: Boolean; const ADriverType: TDBDriverType): string;
var
  SQL: string;
begin
  SQL := 'DROP TABLE ';
  if ADropIfExists then
    SQL := SQL + 'IF EXISTS ';

  SQL := SQL + FormatQualifiedTableName(ASchema, ATable, ADriverType);

  if ACascade and (ADriverType = dtPostgreSQL) then
    SQL := SQL + ' CASCADE';

  Result := SQL + ';';
end;

class function TDDLGenerator.GenerateDropView(const ASchema, AView: string; const ADropIfExists: Boolean; const ADriverType: TDBDriverType): string;
var
  SQL: string;
begin
  SQL := 'DROP VIEW ';
  if ADropIfExists then
    SQL := SQL + 'IF EXISTS ';

  SQL := SQL + FormatQualifiedTableName(ASchema, AView, ADriverType);
  Result := SQL + ';';
end;

class function TDDLGenerator.GenerateAddColumn(const ASchema, ATable: string; AColumn: TSchemaColumn; const ADriverType: TDBDriverType): string;
begin
  Result := Format('ALTER TABLE %s ADD COLUMN %s;', [
    FormatQualifiedTableName(ASchema, ATable, ADriverType),
    FormatColumnDefinition(AColumn, ADriverType)
  ]);
end;

class function TDDLGenerator.GenerateDropColumn(const ASchema, ATable, AColumnName: string; const ADriverType: TDBDriverType): string;
begin
  Result := Format('ALTER TABLE %s DROP COLUMN %s;', [
    FormatQualifiedTableName(ASchema, ATable, ADriverType),
    QuoteIdent(AColumnName, ADriverType)
  ]);
end;

class function TDDLGenerator.GenerateDropIndex(const ASchema, AIndexName, ATableName: string; const ADriverType: TDBDriverType): string;
begin
  case ADriverType of
    dtMySQL, dtMariaDB:
      Result := Format('DROP INDEX %s ON %s;', [
        QuoteIdent(AIndexName, ADriverType),
        FormatQualifiedTableName(ASchema, ATableName, ADriverType)
      ]);
    dtPostgreSQL, dtSQLite, dtFirebird:
    begin
      if (ASchema <> '') and (ADriverType = dtPostgreSQL) then
        Result := Format('DROP INDEX %s.%s;', [QuoteIdent(ASchema, ADriverType), QuoteIdent(AIndexName, ADriverType)])
      else
        Result := Format('DROP INDEX %s;', [QuoteIdent(AIndexName, ADriverType)]);
    end;
  end;
end;

class function TDDLGenerator.GenerateTruncateTable(const ASchema, ATable: string; const ADriverType: TDBDriverType): string;
begin
  if ADriverType = dtSQLite then
    Result := Format('DELETE FROM %s;', [FormatQualifiedTableName(ASchema, ATable, ADriverType)])
  else
    Result := Format('TRUNCATE TABLE %s;', [FormatQualifiedTableName(ASchema, ATable, ADriverType)]);
end;

end.

